# Default values for zabbix.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# with this dict, you can set unified DB access credentials, IP and so on for both Zabbix server and Zabbix web frontend
# you can either chose from having all this in one named (preexisting) secret or setting the values one by one with vars
# whatever set here overrides the credential settings within the "zabbixserver" and "zabbixweb" sections.
db_access:
  # -- under this section you can configure DB access and credentials centrally for the entire helm chart.
  # -- All relevant components installed by this chart will respect it: zabbixserver, zabbixweb and postgresql (if enabled)
  # 
  # -- USING A SECRET
  # -- DB access details all in one existing secret (matches the structure of secrets the CrunchyData pgo operator generates)
  # -- if this option is chosen the below listed "DB_SERVER_*" and "POSTGRES_*" settings are being ignored
  # -- the secret must contain the following keys:
  # -- * host
  # -- * port
  # -- * dbname
  # -- * user
  # -- * password
  secret_name: zabbixdb-pguser-zabbix
  # -- automatically create secret if not already present (works only in combination with postgresql.enabled=true)
  secret_autocreate: true
  #
  # -- If you do NOT want to use a secret for all settings, you can still either set the credentials manually here for all
  # -- components at once, or if left uncommented, set the credentials for each of the components manually
  # -- Address of database host - ignored if postgresql.enabled=true
  #DB_SERVER_HOST: "zabbix-postgresql"
  # -- Port of database host - ignored if postgresql.enabled=true
  #DB_SERVER_PORT: "5432"
  # -- User of database
  #POSTGRES_USER: "zabbix"
  # -- Password of database
  #POSTGRES_PASSWORD: "zabbix"
  # -- Name of database
  #POSTGRES_DB: "zabbix"

# **Zabbix Server** configurations
zabbixserver:
  # -- Enables use of **Zabbix Server**
  enabled: true
  # -- Number of replicas of ``zabbixserver`` module
  replicaCount: 1
  # -- set permissive podAntiAffinity to spread replicas over cluster nodes if replicaCount>1
  pod_anti_affinity: true
  # -- optional set true open a port direct on node where zabbix server runs 
  hostPort: false
  # -- optional set hostIP different from 0.0.0.0 to open port only on this IP
  hostIP: 0.0.0.0
  resources: {}
  image:
    # -- Zabbix server Docker image name
    repository: zabbix/zabbix-server-pgsql
    # -- Tag of Docker image of Zabbix server
    tag: ubuntu-6.0.4
    # -- Pull policy of Docker image
    pullPolicy: IfNotPresent
    # -- List of dockerconfig secrets names to use when pulling images
    pullSecrets: []
  # -- automatically clean orphaned ha nodes from ha_nodes db table
  ha_nodes_autoclean:
    enabled: true
    image:
      repository: postgres
      tag: "14"
      pullPolicy: IfNotPresent
      pullSecrets: []
    schedule: "0 1 * * *"
    delete_older_than_seconds: 3600
  # -- Address of database host
  #DB_SERVER_HOST: "zabbix-postgresql"
  # -- Port of database host
  #DB_SERVER_PORT: "5432"
  # -- User of database
  #POSTGRES_USER: "zabbix"
  # -- Password of database
  #POSTGRES_PASSWORD: "zabbix"
  # -- Name of a secret used for Postgres Password, if set, it overrules the POSTGRES_PASSWORD value
  #POSTGRES_PASSWORD_SECRET: ""
  # -- Key of the secret used for Postgres Password, requires POSTGRES_PASSWORD_SECRET, defaults to password
  #POSTGRES_PASSWORD_SECRET_KEY: "password"
  # -- Name of database
  #POSTGRES_DB: "zabbix"
  service:
    # -- Type of service in Kubernetes cluster
    type: ClusterIP
    # -- Cluster IP for Zabbix server
    clusterIP:
    # -- Port of service in Kubernetes cluster
    port: 10051
    # -- NodePort of service on each node
    nodePort: 31051
    # -- Annotations for the zabbix-server service
    annotations: {}
    # metallb.universe.tf/address-pool: production-public-ips
  # -- Extra environment variables. A list of additional environment variables. See example: https://github.com/cetic/helm-zabbix/blob/master/docs/example/kind/values.yaml
  extraEnv: []
    #- name: ENABLE_TIMESCALED
    #  value: "true"

# **PostgreSQL** configurations
postgresql:
  # -- Create a database using Postgresql
  enabled: true
  image:
    # -- Postgresql Docker image name: chose one of "postgres" or "timescale/timescaledb"
    repository: postgres
    # -- Tag of Docker image of Postgresql server, chose "14" for postgres or "latest-pg14" for timescaledb
    tag: 14
    # -- Pull policy of Docker image
    pullPolicy: IfNotPresent
    # -- List of dockerconfig secrets names to use when pulling images
    pullSecrets: []
  # -- User of database
  #POSTGRES_USER: "zabbix"
  # -- Password of database
  #POSTGRES_PASSWORD: "zabbix"
  # -- Name of database
  #POSTGRES_DB: "zabbix"
  #- max simultaneous connections to accept for the Postgres server
  max_connections: 50
  persistence:
    # -- whether to enable persistent storage for the postgres container or not
    enabled: false
    # -- existing persistent volume claim name to be used to store posgres data
    existing_claim_name: false
    # -- size of the PVC to be automatically generated
    storage_size: 5Gi
    # -- storage PVC storageclass to use
    #storage_class: my-storage-class
  service:
    # -- Type of service in Kubernetes cluster
    type: ClusterIP
    # -- Cluster IP for Zabbix server
    clusterIP: 
    # -- Port of service in Kubernetes cluster
    port: 5432
    # -- Annotations for the zabbix-server service
    annotations: {}
    # metallb.universe.tf/address-pool: production-public-ips
  # -- Extra environment variables. A list of additional environment variables.
  extraEnv: []

# **Zabbix Proxy** configurations
zabbixproxy:
  # -- Enables use of **Zabbix Proxy**
  enabled: true
  # -- Number of replicas of ``zabbixproxy`` module
  replicaCount: 1
  resources: {}
  image:
    # -- Zabbix proxy Docker image name
    repository: zabbix/zabbix-proxy-sqlite3
    # -- Tag of Docker image of Zabbix proxy
    tag: ubuntu-6.0.4
    # -- Pull policy of Docker image
    pullPolicy: IfNotPresent
    # -- List of dockerconfig secrets names to use when pulling images
    pullSecrets: []
  # -- The variable allows to switch Zabbix proxy mode. Bu default, value is 0 - active proxy. Allowed values are 0 and 1.
  ZBX_PROXYMODE: 0
  # -- Zabbix proxy hostname
  # Case sensitive hostname
  ZBX_HOSTNAME: zabbix-proxy # This variable is unique, case sensitive hostname.
  # -- Zabbix server host
  ZBX_SERVER_HOST: zabbix-zabbix-server
  # -- Zabbix server port
  ZBX_SERVER_PORT: 10051
  # ZBX_LOADMODULE: dummy1.so,dummy2.so # The variable is list of comma separated loadable Zabbix modules. It works with volume /var/lib/zabbix/modules.
  # The variable is used to specify debug level, from 0 to 5
  # ZBX_DEBUGLEVEL: 4
  # The variable is used to specify timeout for processing checks. By default, value is 4.
  #ZBX_TIMEOUT: 4

  # -- The variable enable communication with Zabbix Java Gateway to collect Java related checks. By default, value is false.
  ZBX_JAVAGATEWAY_ENABLE: false
  # -- Cache size
  ZBX_VMWARECACHESIZE: 128M
  service:
    # -- Type of service for Zabbix proxy
    type: ClusterIP
    # -- Cluster IP for Zabbix proxy
    clusterIP:
    # -- Port to expose service
    port: 10051
    # -- Annotations for the zabbix-proxy service
    annotations: {}
    # metallb.universe.tf/address-pool: production-public-ips
  # -- Extra environment variables. A list of additional environment variables. See example: https://github.com/cetic/helm-zabbix/blob/master/docs/example/kind/values.yaml
  extraEnv: []

# **Zabbix Agent** configurations
zabbixagent:
  # -- Enables use of **Zabbix Agent**
  enabled: true
  resources: {}
  image:
    # -- Zabbix agent Docker image name. Can use zabbix/zabbix-agent or zabbix/zabbix-agent2
    repository: zabbix/zabbix-agent2
    # -- Tag of Docker image of Zabbix agent
    tag: ubuntu-6.0.4
    # -- Pull policy of Docker image
    pullPolicy: IfNotPresent
    # -- List of dockerconfig secrets names to use when pulling images
    pullSecrets: []
  # -- Zabbix server host
  ZBX_SERVER_HOST: 127.0.0.1
  # -- Zabbix server port
  ZBX_SERVER_PORT: 10051
  # -- This variable is boolean (true or false) and enables or disables feature of passive checks. By default, value is true
  ZBX_PASSIVE_ALLOW: true
  # -- The variable is comma separated list of allowed Zabbix server or proxy hosts for connections to Zabbix agent container.
  ZBX_PASSIVESERVERS: 127.0.0.1
  # -- This variable is boolean (true or false) and enables or disables feature of active checks
  ZBX_ACTIVE_ALLOW: true
  # The variable is comma separated list of allowed Zabbix server or proxy hosts for connections to Zabbix agent container. You may specify port.
  # ZBX_ACTIVESERVERS:
  # The variable is list of comma separated loadable Zabbix modules. It works with volume /var/lib/zabbix/modules.
  # ZBX_LOADMODULE: dummy1.so,dummy2.so
  # The variable is used to specify debug level, from 0 to 5
  #ZBX_DEBUGLEVEL: 3
  # The variable is used to specify timeout for processing checks. By default, value is 4.
  #ZBX_TIMEOUT: 4

  # -- The variable enable communication with Zabbix Java Gateway to collect Java related checks. By default, value is false.
  ZBX_JAVAGATEWAY_ENABLE: false
  # -- Cache size
  ZBX_VMWARECACHESIZE: 128M
  service:
    # -- Type of service for Zabbix agent
    type: ClusterIP
    # -- Cluster IP for Zabbix agent
    clusterIP:
    # -- Port to expose service
    port: 10050
    # -- Annotations for the zabbix-agent service
    annotations: {}
    # metallb.universe.tf/address-pool: production-public-ips
  # -- Extra environment variables. A list of additional environment variables. See example: https://github.com/cetic/helm-zabbix/blob/master/docs/example/kind/values.yaml
  extraEnv: []

# **Zabbix Web** configurations
zabbixweb:
  # -- Enables use of **Zabbix Web**
  enabled: true
  replicaCount: 1
  # -- set permissive podAntiAffinity to spread replicas over cluster nodes if replicaCount>1
  pod_anti_affinity: true
  resources: {}
  image:
    # -- Zabbix web Docker image name
    repository: zabbix/zabbix-web-nginx-pgsql
    # -- Tag of Docker image of Zabbix web
    tag: ubuntu-6.0.4
    # -- Pull policy of Docker image
    pullPolicy: IfNotPresent
    # -- List of dockerconfig secrets names to use when pulling images
    pullSecrets: []
  # -- Zabbix server host
  #DB_SERVER_HOST: zabbix-postgresql
  # -- Port of database
  #DB_SERVER_PORT: 5432
  # -- User of database
  #POSTGRES_USER: zabbix
  # -- Password of database
  #POSTGRES_PASSWORD: zabbix
  # -- Name of database
  #POSTGRES_DB: zabbix
  # -- Name of the Zabbix server in GUI
  #zbx_server_name: something
  service:
    # -- Type of service for Zabbix web
    type: NodePort
    # -- Cluster IP for Zabbix web
    clusterIP:
    # -- Port to expose service
    port: 80
    # -- NodePort port to allocate (only if service.type = NodePort)
    #nodePort: 31080
    # -- Annotations for the zabbix-web service
    annotations: {}
    # metallb.universe.tf/address-pool: production-public-ips
  # -- Extra environment variables. A list of additional environment variables. See example: https://github.com/cetic/helm-zabbix/blob/master/docs/example/kind/values.yaml
  extraEnv: []
  livenessProbe:
    # -- Path of health check of application
    path: /
    # -- Number of seconds after the container has started before liveness
    initialDelaySeconds: 30
    # -- Specifies that the kubelet should perform a liveness probe every N seconds
    periodSeconds: 10
    # -- Number of seconds after which the probe times out
    timeoutSeconds: 5
    # -- When a probe fails, Kubernetes will try failureThreshold times before giving up. Giving up in case of liveness probe means restarting the container. In case of readiness probe the Pod will be marked Unready
    failureThreshold: 6
    # -- Minimum consecutive successes for the probe to be considered successful after having failed
    successThreshold: 1
  readinessProbe:
    # -- Path of health check of application
    path: /
    # -- Number of seconds after the container has started before readiness
    initialDelaySeconds: 5
    # -- Specifies that the kubelet should perform a readiness probe every N seconds
    periodSeconds: 10
    # -- Number of seconds after which the probe times out
    timeoutSeconds: 5
    # -- When a probe fails, Kubernetes will try failureThreshold times before giving up. Giving up in case of liveness probe means restarting the container. In case of readiness probe the Pod will be marked Unready
    failureThreshold: 6
    # -- Minimum consecutive successes for the probe to be considered successful after having failed
    successThreshold: 1

# **Zabbix Web** configurations
zabbixwebservice:
  # -- Enables use of **Zabbix Web Service**
  enabled: true
  replicaCount: 1
  # -- set permissive podAntiAffinity to spread replicas over cluster nodes if replicaCount>1
  pod_anti_affinity: true
  resources: {}
  image:
    # -- Zabbix web Docker image name
    repository: zabbix/zabbix-web-service
    # -- Tag of Docker image of Zabbix web
    tag: ubuntu-6.0.4
    # -- Pull policy of Docker image
    pullPolicy: IfNotPresent
    # -- List of dockerconfig secrets names to use when pulling images
    pullSecrets: []
  # -- set the IgnoreURLCertErrors configuration setting of Zabbix web service
  #ignore_url_cert_errors=1
  service:
    # -- Type of service for Zabbix web
    type: ClusterIP
    # -- Cluster IP for Zabbix web
    clusterIP: 
    # -- Port to expose service
    port: 10053
    # -- Annotations for the zabbix-web service
    annotations: {}
    # metallb.universe.tf/address-pool: production-public-ips
  # -- Extra environment variables. A list of additional environment variables. See example: https://github.com/cetic/helm-zabbix/blob/master/docs/example/kind/values.yaml
  extraEnv: []

# Ingress configurations
ingress:
  # -- Enables Ingress
  enabled: false
  # -- Ingress annotations
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- Ingress extra labels
  extraLabels: {}
  # -- Ingress hosts
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  # -- Ingress TLS configuration
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
  # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
  # ingressClassName: nginx
  # -- pathType is only for k8s >= 1.1=
  pathType: Prefix


# -- nodeSelector configurations
nodeSelector: {}

# -- Tolerations configurations
tolerations: []

# -- Affinity configurations
affinity: {}
