# Default values for zabbix.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# **Zabbix Server** configurations
zabbixserver:
  # -- Enables use of **Zabbix Server**
  enabled: true
  # -- Number of replicas of ``zabbixserver`` module
  replicaCount: 1
  # -- optional set true open a port direct on node where zabbix server runs 
  hostPort: false
  # -- optional set hostIP different from 0.0.0.0 to open port only on this IP
  hostIP: 0.0.0.0
  resources: {}
  image:
    # -- Zabbix server Docker image name
    repository: zabbix/zabbix-server-pgsql
    # -- Tag of Docker image of Zabbix server
    tag: ubuntu-6.0.0
    # -- Pull policy of Docker image
    pullPolicy: IfNotPresent
    # -- List of dockerconfig secrets names to use when pulling images
    pullSecrets: []
  # -- Address of database host
  DB_SERVER_HOST: "zabbix-postgresql"
  # -- Port of database host
  DB_SERVER_PORT: "5432"
  # -- User of database
  POSTGRES_USER: "zabbix"
  # -- Password of database
  POSTGRES_PASSWORD: "zabbix_pwd"
  # -- Name of database
  POSTGRES_DB: "zabbix"
  service:
    # -- Type of service in Kubernetes cluster
    type: ClusterIP
    # -- Cluster IP for Zabbix server
    clusterIP: 
    # -- Port of service in Kubernetes cluster
    port: 10051
    # -- NodePort of service on each node
    nodePort: 31051
  # -- Extra environment variables. A list of additional environment variables. See example: https://github.com/cetic/helm-zabbix/blob/master/docs/example/kind/values.yaml
  extraEnv: {}

# **PostgreSQL** configurations
postgresql:
  # -- Create a database using Postgresql
  enabled: true
  auth:
    # -- Enable remote access to ``postgres`` user
    enablePostgresUser: true
    # -- Password of``postgres`` user in Postgresql
    postgresPassword: "zabbix_pwd"
    # -- User of database
    username: "zabbix"
    # -- Password of database
    password: "zabbix"
    # -- Name of database
    database: "zabbix"

# **Zabbix Proxy** configurations
zabbixproxy:
  # -- Enables use of **Zabbix Proxy**
  enabled: true
  # -- Number of replicas of ``zabbixproxy`` module
  replicaCount: 1
  resources: {}
  image:
    # -- Zabbix proxy Docker image name
    repository: zabbix/zabbix-proxy-sqlite3
    # -- Tag of Docker image of Zabbix proxy
    tag: ubuntu-6.0.0
    # -- Pull policy of Docker image
    pullPolicy: IfNotPresent
    # -- List of dockerconfig secrets names to use when pulling images
    pullSecrets: []
  # -- The variable allows to switch Zabbix proxy mode. Bu default, value is 0 - active proxy. Allowed values are 0 and 1.
  ZBX_PROXYMODE: 0
  # -- Zabbix proxy hostname
  # Case sensitive hostname
  ZBX_HOSTNAME: zabbix-proxy # This variable is unique, case sensitive hostname.
  # -- Zabbix server host
  ZBX_SERVER_HOST: zabbix-zabbix-server
  # -- Zabbix server port
  ZBX_SERVER_PORT: 10051
  # ZBX_LOADMODULE: dummy1.so,dummy2.so # The variable is list of comma separated loadable Zabbix modules. It works with volume /var/lib/zabbix/modules.
  # The variable is used to specify debug level, from 0 to 5
  # ZBX_DEBUGLEVEL: 4
  # The variable is used to specify timeout for processing checks. By default, value is 4.
  #ZBX_TIMEOUT: 4

  # -- The variable enable communication with Zabbix Java Gateway to collect Java related checks. By default, value is false.
  ZBX_JAVAGATEWAY_ENABLE: false
  # -- Cache size
  ZBX_VMWARECACHESIZE: 128M
  service:
    # -- Type of service for Zabbix proxy
    type: ClusterIP
    # -- Cluster IP for Zabbix proxy
    clusterIP: 
    # -- Port to expose service
    port: 10051
  # -- Extra environment variables. A list of additional environment variables. See example: https://github.com/cetic/helm-zabbix/blob/master/docs/example/kind/values.yaml
  extraEnv: {}

# **Zabbix Agent** configurations
zabbixagent:
  # -- Enables use of **Zabbix Agent**
  enabled: true
  resources: {}
  image:
    # -- Zabbix agent Docker image name. Can use zabbix/zabbix-agent or zabbix/zabbix-agent2
    repository: zabbix/zabbix-agent
    # -- Tag of Docker image of Zabbix agent
    tag: ubuntu-6.0.0
    # -- Pull policy of Docker image
    pullPolicy: IfNotPresent
    # -- List of dockerconfig secrets names to use when pulling images
    pullSecrets: []
  # -- Zabbix server host
  ZBX_SERVER_HOST: 127.0.0.1
  # -- Zabbix server port
  ZBX_SERVER_PORT: 10051
  # -- This variable is boolean (true or false) and enables or disables feature of passive checks. By default, value is true
  ZBX_PASSIVE_ALLOW: true
  # -- The variable is comma separated list of allowed Zabbix server or proxy hosts for connections to Zabbix agent container.
  ZBX_PASSIVESERVERS: 127.0.0.1
  # -- This variable is boolean (true or false) and enables or disables feature of active checks
  ZBX_ACTIVE_ALLOW: true
  # The variable is comma separated list of allowed Zabbix server or proxy hosts for connections to Zabbix agent container. You may specify port.
  # ZBX_ACTIVESERVERS:
  # The variable is list of comma separated loadable Zabbix modules. It works with volume /var/lib/zabbix/modules.
  # ZBX_LOADMODULE: dummy1.so,dummy2.so
  # The variable is used to specify debug level, from 0 to 5
  #ZBX_DEBUGLEVEL: 3
  # The variable is used to specify timeout for processing checks. By default, value is 4.
  #ZBX_TIMEOUT: 4

  # -- The variable enable communication with Zabbix Java Gateway to collect Java related checks. By default, value is false.
  ZBX_JAVAGATEWAY_ENABLE: false
  # -- Cache size
  ZBX_VMWARECACHESIZE: 128M
  service:
    # -- Type of service for Zabbix agent
    type: ClusterIP
    # -- Cluster IP for Zabbix agent
    clusterIP: 
    # -- Port to expose service
    port: 10050
  # -- Extra environment variables. A list of additional environment variables. See example: https://github.com/cetic/helm-zabbix/blob/master/docs/example/kind/values.yaml
  extraEnv: {}

# **Zabbix Web** configurations
zabbixweb:
  # -- Enables use of **Zabbix Web**
  enabled: true
  resources: {}
  image:
    # -- Zabbix web Docker image name
    repository: zabbix/zabbix-web-apache-pgsql
    # -- Tag of Docker image of Zabbix web
    tag: ubuntu-6.0.0
    # -- Pull policy of Docker image
    pullPolicy: IfNotPresent
    # -- List of dockerconfig secrets names to use when pulling images
    pullSecrets: []
  # -- Zabbix server host
  ZBX_SERVER_HOST: zabbix-zabbix-server
  # -- Zabbix server port
  ZBX_SERVER_PORT: 10051
  # -- Address of database host
  DB_SERVER_HOST: zabbix-postgresql
  # -- Port of database
  DB_SERVER_PORT: 5432
  # -- User of database
  POSTGRES_USER: zabbix
  # -- Password of database
  POSTGRES_PASSWORD: zabbix_pwd
  # -- Name of database
  POSTGRES_DB: zabbix
  service:
    # -- Type of service for Zabbix web
    type: NodePort
    # -- Cluster IP for Zabbix web
    clusterIP: 
    # -- Port to expose service
    port: 80
  # -- Extra environment variables. A list of additional environment variables. See example: https://github.com/cetic/helm-zabbix/blob/master/docs/example/kind/values.yaml
  extraEnv: {}

# Ingress configurations
ingress:
  # -- Enables Ingress
  enabled: false
  # -- Ingress annotations
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- Ingress extra labels
  extraLabels: {}
  # -- Ingress hosts
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  # -- Ingress TLS configuration
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
  # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
  # ingressClassName: nginx
  # -- pathType is only for k8s >= 1.1=
  pathType: Prefix

livenessProbe:
  # -- Path of health check of application
  path: /
  # -- Number of seconds after the container has started before liveness
  initialDelaySeconds: 30
  # -- Specifies that the kubelet should perform a liveness probe every N seconds
  periodSeconds: 10
  # -- Number of seconds after which the probe times out
  timeoutSeconds: 5
  # -- When a probe fails, Kubernetes will try failureThreshold times before giving up. Giving up in case of liveness probe means restarting the container. In case of readiness probe the Pod will be marked Unready
  failureThreshold: 6
  # -- Minimum consecutive successes for the probe to be considered successful after having failed
  successThreshold: 1

readinessProbe:
  # -- Path of health check of application
  path: /
  # -- Number of seconds after the container has started before readiness
  initialDelaySeconds: 5
  # -- Specifies that the kubelet should perform a readiness probe every N seconds
  periodSeconds: 10
  # -- Number of seconds after which the probe times out
  timeoutSeconds: 5
  # -- When a probe fails, Kubernetes will try failureThreshold times before giving up. Giving up in case of liveness probe means restarting the container. In case of readiness probe the Pod will be marked Unready
  failureThreshold: 6
  # -- Minimum consecutive successes for the probe to be considered successful after having failed
  successThreshold: 1

# -- nodeSelector configurations
nodeSelector: {}

# -- Tolerations configurations
tolerations: []

# -- Affinity configurations
affinity: {}
