---
apiVersion: v2
name: zabbix
version: 3.2.2
# LTS Zabbix version by default due to stability. See: https://www.zabbix.com/life_cycle_and_release_policy
appVersion: 6.0.8
description: Zabbix is a mature and effortless enterprise-class open source monitoring solution for network monitoring and application monitoring of millions of metrics.
keywords:
  - zabbix
  - monitoring
  - metrics
  - kubernetes
  - helm
home: https://www.zabbix.com
icon: https://assets.zabbix.com/img/logo/zabbix_logo_500x131.png
sources:
  - https://github.com/zabbix-community/helm-zabbix
maintainers:
  - name: Aecio Pires
    email: aeciopires@gmail.com
    url: https://github.com/aeciopires
  - name: Christian Anton
    email: christian.anton@secadm.de
    url: https://secadm.de
