---
apiVersion: v2  # Don't change this
name: zabbix
version: 7.0.1  # helm chart version
# LTS Zabbix version by default due to stability. See: https://www.zabbix.com/life_cycle_and_release_policy
appVersion: 7.0.8  # zabbix version
description: Zabbix is a mature and effortless enterprise-class open source monitoring solution for network monitoring and application monitoring of millions of metrics.
keywords:
  - zabbix
  - monitoring
  - metrics
  - kubernetes
  - helm
home: https://www.zabbix.com
icon: https://assets.zabbix.com/img/logo/zabbix_logo_500x131.png
sources:
  - https://github.com/zabbix-community/helm-zabbix
maintainers:
  - name: Aecio Pires
    email: aeciopires@yahoo.com.br
    url: https://github.com/aeciopires
  - name: Christian Anton
    email: christian.anton@inqbeo.de
    url: https://inqbeo.de
