{{- if .Values.zabbixserver.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "zabbix.fullname" . }}-zabbix-server
  labels:
    app: {{ template "zabbix.fullname" . }}-zabbix-server
    app.kubernetes.io/name: zabbix-server
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-server
    app.kubernetes.io/managed-by: {{ .Release.Service }}-zabbix-server
spec:
  replicas: {{ .Values.zabbixserver.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "zabbix.fullname" . }}-zabbix-server
  template:
    metadata:
      labels:
        app: {{ template "zabbix.fullname" . }}-zabbix-server
        app.kubernetes.io/name: zabbix-server
        helm.sh/chart: {{ include "zabbix.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-server
        app.kubernetes.io/managed-by: {{ .Release.Service }}-zabbix-server
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if gt (len .Values.affinity) 0 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- else if .Values.zabbixserver.pod_anti_affinity }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-server
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: zabbix-server
          resources:
{{- toYaml .Values.zabbixserver.resources | nindent 12 }}
          image: {{ .Values.zabbixserver.image.repository }}:{{ .Values.zabbixserver.image.tag }}
          ports:
            - containerPort: 10051
              name: zabbix-server
              {{- if (default false .Values.zabbixserver.hostPort) }}
              hostPort: 10051
              {{- end }}
              {{- if ne "0.0.0.0" .Values.zabbixserver.hostIP }}
              hostIP: {{ .Values.zabbixserver.hostIP }}
              {{- end}}
            - containerPort: 10052
              name: zabbix-jmx
              {{- if (default false .Values.zabbixserver.hostPort) }}
              hostPort: 10052
              {{- end }}
              {{- if ne "0.0.0.0" .Values.zabbixserver.hostIP }}
              hostIP: {{ .Values.zabbixserver.hostIP }}
              {{- end}}
          env:
            {{- if .Values.postgresql.enabled }}
            - name: DB_SERVER_HOST
              value: {{ template "zabbix.fullname" . }}-postgresql
            - name: DB_SERVER_PORT
              value: {{ .Values.postgresql.service.port | quote }}
            {{- else if .Values.db_access.secret_name }}
            - name: DB_SERVER_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db_access.secret_name }}
                  key: host
            - name: DB_SERVER_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db_access.secret_name }}
                  key: port
                  optional: true
            {{- else }}
            - name: DB_SERVER_HOST
              {{- if .Values.db_access.DB_SERVER_HOST }}
              value: {{ .Values.db_access.DB_SERVER_HOST | quote }}
              {{- else }}
              value: {{ .Values.zabbixserver.DB_SERVER_HOST | quote }}
              {{- end }}
            - name: DB_SERVER_PORT
              {{- if .Values.db_access.DB_SERVER_PORT }}
              value: {{ .Values.db_access.DB_SERVER_PORT | quote }}
              {{- else }}
              value: {{ .Values.zabbixserver.DB_SERVER_PORT | quote }}
              {{- end }}
            {{- end }}
            {{- if .Values.db_access.secret_name }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db_access.secret_name }}
                  key: user
                  optional: true
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db_access.secret_name }}
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db_access.secret_name }}
                  key: dbname
                  optional: true
            {{- else }}
            - name: POSTGRES_USER
              {{- if .Values.db_access.POSTGRES_USER }}
              value: {{ .Values.db_access.POSTGRES_USER | quote }}
              {{- else }}
              value: {{ .Values.zabbixserver.POSTGRES_USER | quote }}
              {{ end }}
            - name: POSTGRES_PASSWORD
              {{- if .Values.db_access.POSTGRES_PASSWORD }}
              value: {{ .Values.db_access.POSTGRES_PASSWORD | quote }}
              {{- else if .Values.zabbixserver.POSTGRES_PASSWORD_SECRET }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.zabbixserver.POSTGRES_PASSWORD_SECRET }}
                  key: {{ default "password" .Values.zabbixserver.POSTGRES_PASSWORD_SECRET_KEY }}
              {{- else }}
              value: {{ .Values.zabbixserver.POSTGRES_PASSWORD | quote }}
              {{- end }}
            - name: POSTGRES_DB
              {{- if .Values.db_access.POSTGRES_DB }}
              value: {{ .Values.db_access.POSTGRES_DB | quote }}
              {{- else }}
              value: {{ .Values.zabbixserver.POSTGRES_DB | quote }}
              {{- end }}
            {{- end }}
            {{- range $item := .Values.zabbixserver.extraEnv }}
            - name: {{ $item.name }}
              value: {{ $item.value | quote }}
            {{- end }}
            - name: ZBX_AUTOHANODENAME
              value: "hostname"
            - name: ZBX_NODEADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- if .Values.zabbixwebservice.enabled }}
            - name: ZBX_WEBSERVICEURL
              value: "http://{{ template "zabbix.fullname" . }}-zabbix-webservice:{{ .Values.zabbixwebservice.service.port }}/report"
            - name: ZBX_STARTREPORTWRITERS
              value: {{ .Values.zabbixwebservice.replicaCount|quote }}
            {{- end }}
        {{- if .Values.zabbixagent.enabled }}
        - name: zabbix-agent
          resources:
{{- toYaml .Values.zabbixagent.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.zabbixagent.image.repository }}:{{ .Values.zabbixagent.image.tag }}"
          imagePullPolicy: {{ .Values.zabbixagent.image.pullPolicy }}
          env:
            - name: ZBX_HOSTNAME
              value: "Zabbix server"
            - name: ZBX_SERVER_HOST
              value: {{ .Values.zabbixagent.ZBX_SERVER_HOST | quote }}
            - name: ZBX_SERVER_PORT
              value: {{ .Values.zabbixagent.ZBX_SERVER_PORT | quote }}
            - name: ZBX_PASSIVE_ALLOW
              value: {{ .Values.zabbixagent.ZBX_PASSIVE_ALLOW | quote }}
            - name: ZBX_PASSIVESERVERS
              value: {{ .Values.zabbixagent.ZBX_PASSIVESERVERS | quote }}
            - name: ZBX_ACTIVE_ALLOW
              value: {{ .Values.zabbixagent.ZBX_ACTIVE_ALLOW | quote }}
            - name: ZBX_ACTIVESERVERS
              value: {{ .Values.zabbixagent.ZBX_ACTIVESERVERS | quote }}
            - name: ZBX_DEBUGLEVEL
              value: {{ .Values.zabbixagent.ZBX_DEBUGLEVEL | quote }}
            - name: ZBX_TIMEOUT
              value: {{ .Values.zabbixagent.ZBX_TIMEOUT | quote }}
            - name: ZBX_LOADMODULE
              value: {{ .Values.zabbixagent.ZBX_LOADMODULE }}
            {{- range $item := .Values.zabbixagent.extraEnv }}
            - name: {{ $item.name }}
              value: {{ $item.value | quote }}
            {{- end }}
          ports:
            - name: zabbix-agent
              containerPort: 10050
              protocol: TCP
        {{- end }}
      imagePullSecrets:
      {{- range .Values.zabbixserver.image.pullSecrets }}
        - name: {{ . | quote }}
      {{- end }}
      {{- range .Values.zabbixagent.image.pullSecrets }}
        - name: {{ . | quote }}
      {{- end }}
{{- end }}
