{{- if .Values.zabbixserver.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "zabbix.fullname" . }}-zabbix-server
  labels:
    app: {{ template "zabbix.fullname" . }}-zabbix-server
    app.kubernetes.io/name: zabbix-server
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-server
    app.kubernetes.io/managed-by: {{ .Release.Service }}-zabbix-server
  {{- if .Values.zabbixserver.service.annotations }}
  annotations:
    {{- range $key,$value := .Values.zabbixserver.service.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.zabbixserver.service.type }}
  {{- if .Values.zabbixserver.service.clusterIP }}
  clusterIP: {{ .Values.zabbixserver.service.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.zabbixserver.service.port }}
      targetPort: 10051
      name: zabbix-server
      protocol: TCP
      {{- if and .Values.zabbixserver.service.nodePort (eq .Values.zabbixserver.service.type "NodePort") }}
      nodePort: {{ .Values.zabbixserver.service.nodePort }}
      {{- end }}
    - port: 10052
      targetPort: 10052
      protocol: TCP
      name: zabbix-jmx
  selector:
    app: {{ template "zabbix.fullname" . }}-zabbix-server
{{- end }}


{{- if .Values.zabbixagent.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "zabbix.fullname" . }}-zabbix-agent
  labels:
    app: {{ template "zabbix.fullname" . }}-zabbix-agent
    app.kubernetes.io/name: zabbix-agent
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-agent
    app.kubernetes.io/managed-by: {{ .Release.Service }}-zabbix-agent
  {{- if .Values.zabbixagent.service.annotations }}
  annotations:
    {{- range $key,$value := .Values.zabbixagent.service.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.zabbixagent.service.type }}
  {{- if .Values.zabbixagent.service.clusterIP }}
  clusterIP: {{ .Values.zabbixagent.service.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.zabbixagent.service.port }}
      targetPort: 10050
      protocol: TCP
      name: zabbix-agent
  selector:
    app: {{ template "zabbix.fullname" . }}-zabbix-server
{{- end }}


{{- if .Values.zabbixweb.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "zabbix.fullname" . }}-zabbix-web
  labels:
    app: {{ template "zabbix.fullname" . }}-zabbix-web
    app.kubernetes.io/name: zabbix-web
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-web
    app.kubernetes.io/managed-by: {{ .Release.Service }}-zabbix-web
  {{- if .Values.zabbixweb.service.annotations }}
  annotations:
    {{- range $key,$value := .Values.zabbixweb.service.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.zabbixweb.service.type }}
  {{- if .Values.zabbixweb.service.clusterIP }}
  clusterIP: {{ .Values.zabbixweb.service.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.zabbixweb.service.port }}
      targetPort: 8080
      protocol: TCP
      name: zabbix-web
  selector:
    app: {{ template "zabbix.fullname" . }}-zabbix-web
  {{- end }}


{{- if .Values.zabbixproxy.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "zabbix.fullname" . }}-zabbix-proxy
  labels:
    app: {{ template "zabbix.fullname" . }}-zabbix-proxy
    app.kubernetes.io/name: zabbix-proxy
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-proxy
    app.kubernetes.io/managed-by: {{ .Release.Service }}-zabbix-proxy
  {{- if .Values.zabbixproxy.service.annotations }}
  annotations:
    {{- range $key,$value := .Values.zabbixproxy.service.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.zabbixproxy.service.type }}
  {{- if .Values.zabbixproxy.service.clusterIP }}
  clusterIP: {{ .Values.zabbixproxy.service.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.zabbixproxy.service.port }}
      targetPort: 10051
      protocol: TCP
      name: zabbix-proxy
  selector:
    app: {{ template "zabbix.fullname" . }}-zabbix-proxy
{{- end }}

{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "zabbix.fullname" . }}-postgresql
  labels:
    app: {{ template "zabbix.fullname" . }}-postgresql
    app.kubernetes.io/name: postgresql
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-postgresql
    app.kubernetes.io/managed-by: {{ .Release.Service }}-postgresql
  {{- if .Values.postgresql.service.annotations }}
  annotations:
    {{- range $key,$value := .Values.postgresql.service.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.postgresql.service.type }}
  {{- if .Values.postgresql.service.clusterIP }}
  clusterIP: {{ .Values.postgresql.service.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: 5432
      protocol: TCP
      name: db
  selector:
    app: {{ template "zabbix.fullname" . }}-postgresql
{{- end }}