---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  labels:
    app: zabbix-server
    app.kubernetes.io/name: zabbix-server
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  type: {{ .Values.zabbixServer.service.type }}
  ports:
    - port: 10051
      targetPort: 10051
      name: zabbix-server
    - port: 10052
      targetPort: 10052
      name: zabbix-jmx
  selector:
    app: zabbix-server
---
  {{- if .Values.zabbixagent.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: zabbix-agent
  labels:
    app: zabbix-agent
    app.kubernetes.io/name: zabbix-agent
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-agent
    app.kubernetes.io/managed-by: {{ .Release.Service }}-agent
spec:
  type: {{ .Values.zabbixagent.service.type }}
  ports:
    - port: {{ .Values.zabbixagent.service.port }}
      targetPort: {{ .Values.zabbixagent.service.targetPort }}
      protocol: TCP
      name: zabbix-agent
  selector:
    app: zabbix-agent
    {{- end }}
---
  {{- if .Values.zabbixweb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-zabbix-web
  labels:
      app: zabbix-web
      app.kubernetes.io/name: zabbix-web
      helm.sh/chart: {{ include "zabbix.chart" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}-web
      app.kubernetes.io/managed-by: {{ .Release.Service }}-web
spec:
  type: {{ .Values.zabbixweb.service.type }}
  ports:
    - port: {{ .Values.zabbixweb.service.port }}
      targetPort: {{ .Values.zabbixweb.service.targetPort }}
      protocol: TCP
      name: zabbix-web
  selector:
    app: zabbix-web
  {{- end }}
---
  {{- if .Values.zabbixproxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: zabbix-proxy
  labels:
    app: zabbix-proxy
    app.kubernetes.io/name: zabbix-proxy
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-proxy
    app.kubernetes.io/managed-by: {{ .Release.Service }}-proxy
spec:
  ports:
    - port: {{ .Values.zabbixproxy.service.port }}
      targetPort: {{ .Values.zabbixproxy.service.targetPort }}
      name: zabbix-proxy
  selector:
    app: zabbix-proxy
    {{- end }}