{{- if not .Values.postgresAccess.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "zabbix.fullname" . }}-db-access
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ template "zabbix.fullname" . }}-db-access
    app.kubernetes.io/name: db-access
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-db-access
    app.kubernetes.io/managed-by: {{ .Release.Service }}-db-access
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace .Values.postgresAccess.existingSecretName) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $secretHost := (get $secretData .Values.postgresAccess.secretHostKey) | default (default (printf "%s-%s" (include "zabbix.fullname" .) "postgresql") .Values.postgresAccess.host | b64enc) }}
  {{- $secretPort := (get $secretData .Values.postgresAccess.secretPortKey) | default (.Values.postgresql.service.port | toString | b64enc) }}
  {{- $secretDbname := (get $secretData .Values.postgresAccess.secretDBKey) | default ( default "zabbix" .Values.postgresAccess.database | b64enc) }}
  {{- $secretUser := (get $secretData .Values.postgresAccess.secretUserKey) | default (default "zabbix" .Values.postgresAccess.user | b64enc) }}
  {{- $secretPassword := (get $secretData .Values.postgresAccess.secretPasswordKey) | default (default (randAlphaNum 16) .Values.postgresAccess.password | b64enc) }}
  {{- $secretSchema := "" }}
  {{- if and (not .Values.postgresql.enabled) .Values.postgresAccess.secretSchemaKey }}
  {{- $secretSchema = (get $secretData .Values.postgresAccess.secretSchemaKey) | default (default "public" .Values.postgresAccess.schema | b64enc )}}
  {{- end }}
  {{ .Values.postgresAccess.secretHostKey }}: {{ $secretHost | quote }}
  {{ .Values.postgresAccess.secretPortKey }}: {{ $secretPort | quote }}
  {{ .Values.postgresAccess.secretDBKey }}: {{ $secretDbname | quote }}
  {{ .Values.postgresAccess.secretUserKey }}: {{ $secretUser | quote }}
  {{ .Values.postgresAccess.secretPasswordKey }}: {{ $secretPassword | quote }}
  {{- if $secretSchema }}
  {{ .Values.postgresAccess.secretSchemaKey }}: {{ $secretSchema | quote }}
  {{- end }}
{{- end }}
