{{- if or .Values.serviceAccount.create ( and .Values.zabbixServer.enabled .Values.zabbixServer.zabbixServerHA.enabled ) }}
apiVersion: v1
kind: ServiceAccount
{{- with .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ template "zabbix.serviceAccountName" . }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ template "zabbix.fullname" . }}-serviceaccount
    {{- include "zabbix.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
