{{- if .Values.postgresql.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "zabbix.fullname" . }}-postgresql
  labels:
    {{- include "zabbix.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
    {{- if .Values.postgresql.extraStatefulSetLabels }}
    {{- toYaml .Values.postgresql.extraStatefulSetLabels | nindent 4 }}
    {{- end }}
  annotations:
    {{- range $key,$value := .Values.postgresql.extraStatefulSetAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if .Values.postgresql.persistence.enabled }}
  {{- if not .Values.postgresql.persistence.existingClaimName }}
  volumeClaimTemplates:
    - metadata:
        name: postgresql-data
      spec:
        accessModes:
          {{- if .Values.postgresql.persistence.claim_access_mode }}
          - {{ .Values.postgresql.persistence.claim_access_mode }}
          {{- else }}
          - ReadWriteOnce
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgresql.persistence.storageSize }}
        {{- if .Values.postgresql.persistence.storageClass }}
        storageClassName: {{ .Values.postgresql.persistence.storageClass }}
        {{- end }}
  {{- end }}
  {{- end }}
  replicas: 1
  serviceName: {{ template "zabbix.fullname" . }}
  selector:
    matchLabels:
      {{- include "zabbix.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgresql
  template:
    metadata:
      annotations:
        {{- range $key,$value := .Values.postgresql.extraPodAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      labels:
        {{- include "zabbix.labels" . | nindent 8 }}
        app.kubernetes.io/component: postgresql
        {{- if .Values.postgresql.extraPodLabels }}
        {{- toYaml .Values.postgresql.extraPodLabels | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "zabbix.serviceAccountName" . }}
      {{- with .Values.postgresql.extraPodSpecs }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.postgresql.extraInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: postgresql
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.postgresql.securityContext | nindent 12 }}
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          {{- with .Values.postgresql.extraRuntimeParameters }}
          args:
            {{- range $key, $value := . }}
            - "-c"
            - "{{ $key }}={{ $value }}"
            {{- end }}
          {{- end }}
          env:
            {{- include "zabbix.postgresAccess.variables" (list $ . "database") | nindent 12 }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            {{- with .Values.postgresql.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
          {{- if .Values.postgresql.persistence.enabled }}
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
          {{- end }}
          {{- with .Values.postgresql.extraVolumeMounts }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: db
              containerPort: 5432
              protocol: TCP
          {{- with .Values.postgresql.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.postgresql.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.postgresql.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.postgresql.extraContainers }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.postgresql.persistence.enabled }}
      {{- if .Values.postgresql.persistence.existingClaimName }}
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: {{ .Values.postgresql.persistence.existingClaimName }}
      {{- end }}
      {{- end }}
      {{- with .Values.postgresql.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
      {{- range .Values.postgresql.image.pullSecrets }}
        - name: {{ . | quote }}
      {{- end }}
{{- end }}
